title: BUILD Notes
description: I want to write it down, and for it to be pretty.
baseurl: "/build-notes"
url: ""
repository: buildsi/build-notes
paginate: 28

# Repository folder (private) with papers
papers_url: https://github.com/LLNL/build-bib/blob/main/papers

banner: "/assets/img/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/img/favicon.ico" # site's favicon (icon left side of your page)

# Collections
collections:
  papers:
    output: true
    permalink: /:collection/:path
  notes:
    output: true
    permalink: /:collection/:path
  terms:
    output: true
    permalink: /:collection/:path
  paper-details:
    output: true
    permalink: /:collection/:path
    collections_dir: paper-details


defaults:
  - scope:
      path: "_papers"
      type: "papers"
    values:
      layout: "paper"
  - scope:
      path: "_terms"
      type: "terms"
    values:
      layout: "post"
  - scope:
      path: "_notes"
      type: "notes"
    values:
      layout: "post"

user: 
  avatar: "/assets/img/logo.png"
  github: "buildsi"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

scholar:
  style: _bibliography/my-ieee.cls
  bibliography: references.bib
# TODO need to figure out how to add prefix here
  bibliography_template: bibitem-template
  details_dir: "paper-details"
  details_layout: "details.html"
#  details_permalink: "/notes-jekyll/:details_dir/:key:extension"
# Ensure that details are not printed twice
  details_link: ""

